name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [linux, darwin]
        arch: [amd64]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          mkdir bin
          go build -v -o "bin/bob-$GOOS-$GOARCH-$GITHUB_REF_NAME"

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: bin/

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 19.0.2
          branch: main
          extra_plugins: |
              @semantic-release/commit-analyzer
              @semantic-release/release-notes-generator
              @semantic-release/github