name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          mkdir bin
          go build -v -o "bin/bob-$GOOS-$GOARCH-$GITHUB_REF_NAME"

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/*

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Set up CodeClimate
        run: |
          curl -LO https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x ./test-reporter-latest-linux-amd64
          ./test-reporter-latest-linux-amd64 before-build

      - name: Run Tests
        run: go test ./... -coverprofile c.out

      - name: Upload to CodeClimate
        run: ./test-reporter-latest-linux-amd64 after-build --prefix github.com/vitorfhc/bob/
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [build, tests]
    steps:
      - uses: actions/checkout@v3
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: bin/

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 19.0.2
          branch: main
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
